# Generated by Django 4.1.2 on 2022-11-03 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Comment', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(max_length=100, unique=True)),
                ('subject_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('subject_description', models.TextField(max_length=300)),
                ('subject_image', models.ImageField(upload_to='base/subject_img')),
                ('teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.CharField(max_length=100, unique=True)),
                ('lesson_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('position', models.PositiveSmallIntegerField(verbose_name='lesson num')),
                ('lesson_image', models.ImageField(upload_to='base/lesson_img')),
                ('video', models.FileField(upload_to='base/videos')),
                ('video_text', models.FileField(upload_to='base/PDF_course')),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relate', to='pages.subject')),
            ],
        ),
    ]
